services:
  - type: web
    name: portfolio-dotnet-api
    env: dotnet
    region: oregon
    plan: free
    buildCommand: dotnet build
    startCommand: dotnet Portfolio.API.dll
    rootDir: .
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: ${DB_CONNECTION_STRING}
